name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      sha:
        desciption: 'The test commit SHA or ref'
        required: true
        default: 'master'
      merged_sha:
        description: 'The merge commit SHA' 
      deploy_run_id:
        description: 'The ID of a deployment workspace run with artifacts'

jobs:
  publish:
    if: ${{ !github.event.release.draft }}
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: DevExpress/testcafe-build-system/actions/publish-with-publish-please@main
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        with:
          token: ${{ secrets.NPM_TOKEN }}